input_path: "input"

ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 104
  # Genome build
  build: GRCh37


annotations:
  vep:
    # Consider removing --everything if VEP is slow for you (e.g. for WGS), 
    # and think carefully about which annotations you need.
    params: "--hgvsg --hgvs"
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
