general:
  file_age: 5 #In minutes
  input_path: "input"
  output_path: "output"


ref:
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 104
  # Genome build
  build: GRCh37


annotations:
  vep:
    # Consider removing --everything if VEP is slow for you (e.g. for WGS), 
    # and think carefully about which annotations you need.
    params: "--hgvsg --hgvs --refseq"
    plugins: ""
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".

filter: "CSQ['Feature'] in ['NM_002529', 'NM_006180', 'NM_001012338', 'NM_020975', 'NM_005343', 'NM_000455', 'NM_203500', 'NM_004304', 'NM_004333', 'NM_001904', 'NM_005228', 'NM_023110', 'NM_022970', 'NM_000142', 'NM_213647', 'NM_004448', 'NM_033360', 'NM_002755', 'NM_001127500', 'NM_002524', 'NM_006218', 'NM_000314', 'NM_000546', 'NM_002944', 'NM_005896', 'NM_002168'] or (CSQ['Feature'] == 'NM_000141' and CSQ['EXON'] == '8/18')"